import mongoose from "mongoose";

const MONGODB_URI =
  "mongodb+srv://abbasimusa1106_db_user:a2J2QaRAxhsYcLUd@cluster0.hjnciwe.mongodb.net/yacumart?retryWrites=true&w=majority";

const ArtworkSchema = new mongoose.Schema(
  {
    slug: { type: String, unique: true, required: true },
    title: { type: String, required: true },
    verseId: { type: String, required: true },
    arabic: { type: String, required: true },
    transliteration: { type: String },
    translation: { type: String, required: true },
    tafsir: { type: String },
    surah: { type: String },
    surahNumber: { type: Number },
    ayah: { type: Number },
    theme: { type: String, required: true },
    previewImageUrl: { type: String, required: true },
    highResS3Key: { type: String, required: true },
    qrCodeImageUrl: { type: String },
    digitalPrice: { type: Number, required: true },
    printPriceBase: { type: Number, required: true },
    printSizes: [
      {
        label: String,
        dimensions: String,
        price: Number,
      },
    ],
    frameOptions: [
      {
        label: String,
        material: String,
        priceAddon: Number,
      },
    ],
    status: {
      type: String,
      enum: ["draft", "published", "soldout"],
      default: "published",
    },
    orientation: { type: String, enum: ["vertical", "horizontal"], default: "vertical" },
    description: { type: String },
    isAuctionPiece: { type: Boolean, default: false },
    isFeatured: { type: Boolean, default: false },
  },
  { timestamps: true }
);

const Artwork =
  mongoose.models.Artwork || mongoose.model("Artwork", ArtworkSchema);

const defaultPrintSizes = [
  { label: "Small", dimensions: '12" × 16"', price: 149900 },
  { label: "Medium", dimensions: '18" × 24"', price: 249900 },
  { label: "Large", dimensions: '24" × 36"', price: 399900 },
];

const defaultFrameOptions = [
  { label: "No Frame", material: "Unframed", priceAddon: 0 },
  { label: "Black Wood", material: "Solid Black Wood", priceAddon: 99900 },
  { label: "Gold Metal", material: "Brushed Gold Metal", priceAddon: 149900 },
  { label: "Walnut", material: "Natural Walnut Wood", priceAddon: 129900 },
];

const artworks = [
  {
    slug: "sibghatallah-take-on-allahs-colour",
    title: "Sibghatallah",
    verseId: "al-baqarah-2-138",
    arabic: "صِبْغَةَ ٱللَّهِ ۖ وَمَنْ أَحْسَنُ مِنَ ٱللَّهِ صِبْغَةً ۖ وَنَحْنُ لَهُ عَـٰبِدُونَ",
    transliteration: "Sibghatallāhi wa man aḥsanu minallāhi sibghatan wa naḥnu lahū ʿābidūn",
    translation:
      '"Take on Allah\'s colour." And whose colour is better than Allah\'s? It is Him that we serve.',
    tafsir:
      "Ibn Kathir explains that 'Sibghah' (colour/dye) of Allah refers to the fitrah — the natural disposition of faith that Allah created in every human being. Just as a dye transforms cloth completely, Islam transforms the believer's entire being. The verse challenges: who can offer a better transformation than the one Allah provides? It is a call to embrace the pure faith of Ibrahim (AS) fully, letting it colour every aspect of life — thoughts, actions, and worship.",
    surah: "Al-Baqarah",
    surahNumber: 2,
    ayah: 138,
    theme: "Light",
    previewImageUrl: "/artworks/sibghatallah.png",
    highResS3Key: "artworks/sibghatallah-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    status: "published",
    isAuctionPiece: false,
    isFeatured: true,
    description:
      "A vast, ethereal desert landscape where divine light descends like a luminous waterfall, painting veins of colour through ancient stone. The barren earth awakens with subtle hues — a visual meditation on how Allah's colour transforms even the most desolate terrain into something sacred and alive.",
  },
  {
    slug: "thornless-lote-trees-sidrin-makhdud",
    title: "Thornless Lote Trees",
    verseId: "al-waqiah-56-28",
    arabic: "فِى سِدْرٍ مَّخْضُودٍ",
    transliteration: "Fī sidrim makhdūd",
    translation:
      "They shall be in the midst of thornless lote trees.",
    tafsir:
      "The Lote Tree (Sidr) in this world has thorns, but in Paradise, Allah removes every trace of harm and discomfort. The scholars of tafsir explain that 'makhdud' means the thorns have been stripped away and replaced with fruit. This is a metaphor for the afterlife itself — everything painful in this world is transformed into pure comfort and beauty. Ibn Abbas (RA) said the fruits of this tree are larger and sweeter than anything known on earth.",
    surah: "Al-Waqi'ah",
    surahNumber: 56,
    ayah: 28,
    theme: "Nature",
    previewImageUrl: "/artworks/thornless-lote-trees.png",
    highResS3Key: "artworks/thornless-lote-trees-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    status: "published",
    isAuctionPiece: false,
    isFeatured: true,
    description:
      "A serene vision of Paradise: beneath thornless lote trees, the gardens glow with peace, soft light, and flowing streams, offering a glimpse of the comfort and beauty prepared for the blessed.",
  },
  {
    slug: "divine-precision-sunflower",
    title: "Divine Precision — Sunflower",
    verseId: "al-mulk-67-3",
    arabic: "ٱلَّذِى خَلَقَ سَبْعَ سَمَـٰوَٰتٍ طِبَاقًا ۖ مَّا تَرَىٰ فِى خَلْقِ ٱلرَّحْمَـٰنِ مِن تَفَـٰوُتٍ ۖ فَٱرْجِعِ ٱلْبَصَرَ هَلْ تَرَىٰ مِن فُطُورٍ",
    transliteration: "Alladhī khalaqa sabʿa samāwātin ṭibāqan mā tarā fī khalqir-raḥmāni min tafāwut. Farjiʿil-baṣara hal tarā min fuṭūr",
    translation:
      "Who created the seven heavens one upon another. You will not see any inconsistency in the Merciful One's creation. Turn your vision again, can you see any flaw?",
    tafsir:
      "This verse invites humanity to observe the universe — not casually, but with deep reflection. Allah challenges us to look at the heavens repeatedly, searching for any crack, imbalance, or defect. The more one looks, the more perfect the design appears. The scholars note that 'tafawut' means disproportion or inconsistency. From the spirals of galaxies to the veins of a sunflower petal, the same mathematical precision appears. It is a sign that points to One Creator — Al-Rahman, the Most Merciful.",
    surah: "Al-Mulk",
    surahNumber: 67,
    ayah: 3,
    theme: "Creation",
    previewImageUrl: "/artworks/sunflower-closeup.png",
    highResS3Key: "artworks/sunflower-closeup-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    status: "published",
    isAuctionPiece: false,
    isFeatured: false,
    description:
      "The perfection of Allah's creation: layered, balanced, and without fault. It invites the heart to look again and again, finding harmony, beauty, and signs of divine design in every detail.",
  },
  {
    slug: "divine-precision-leaf",
    title: "Divine Precision — Leaf",
    verseId: "al-mulk-67-3-leaf",
    arabic: "ٱلَّذِى خَلَقَ سَبْعَ سَمَـٰوَٰتٍ طِبَاقًا ۖ مَّا تَرَىٰ فِى خَلْقِ ٱلرَّحْمَـٰنِ مِن تَفَـٰوُتٍ ۖ فَٱرْجِعِ ٱلْبَصَرَ هَلْ تَرَىٰ مِن فُطُورٍ",
    transliteration: "Alladhī khalaqa sabʿa samāwātin ṭibāqan mā tarā fī khalqir-raḥmāni min tafāwut. Farjiʿil-baṣara hal tarā min fuṭūr",
    translation:
      "Who created the seven heavens one upon another. You will not see any inconsistency in the Merciful One's creation. Turn your vision again, can you see any flaw?",
    tafsir:
      "Al-Qurtubi elaborates that this verse is an open invitation to study nature. Every leaf, with its intricate network of veins distributing water and nutrients with mathematical precision, is a testament to divine design. The branching patterns follow the same fractal geometry found across all of creation — in rivers, in lungs, in lightning. No human engineer could replicate such efficiency. The leaf is small, yet it carries the signature of the same Creator who fashioned the seven heavens.",
    surah: "Al-Mulk",
    surahNumber: 67,
    ayah: 3,
    theme: "Creation",
    previewImageUrl: "/artworks/divine-leaf.png",
    highResS3Key: "artworks/divine-leaf-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    status: "published",
    isAuctionPiece: false,
    isFeatured: false,
    description:
      "The perfection of Allah's creation, where no flaw or imbalance can truly be found. Its delicate patterns invite the eye to look again and again, witnessing harmony, beauty, and divine precision in even the smallest part of nature.",
  },
  {
    slug: "radiant-sunflower-divine-design",
    title: "Radiant Sunflower",
    verseId: "al-mulk-67-3-sunflower",
    arabic: "ٱلَّذِى خَلَقَ سَبْعَ سَمَـٰوَٰتٍ طِبَاقًا ۖ مَّا تَرَىٰ فِى خَلْقِ ٱلرَّحْمَـٰنِ مِن تَفَـٰوُتٍ ۖ فَٱرْجِعِ ٱلْبَصَرَ هَلْ تَرَىٰ مِن فُطُورٍ",
    transliteration: "Alladhī khalaqa sabʿa samāwātin ṭibāqan mā tarā fī khalqir-raḥmāni min tafāwut. Farjiʿil-baṣara hal tarā min fuṭūr",
    translation:
      "Who created the seven heavens one upon another. You will not see any inconsistency in the Merciful One's creation. Turn your vision again, can you see any flaw?",
    tafsir:
      "A sunflower's head contains seeds arranged in two interlocking spirals — typically 34 in one direction and 55 in the other — numbers from the Fibonacci sequence. This mathematical order is not random; it is the design of Al-Rahman. As-Sa'di notes that this verse calls believers to move from superficial seeing to deep contemplation (tafakkur). The more science reveals about nature's precision, the louder this verse echoes: there is no flaw in what the Most Merciful has made.",
    surah: "Al-Mulk",
    surahNumber: 67,
    ayah: 3,
    theme: "Creation",
    previewImageUrl: "/artworks/sunflower-garden.png",
    highResS3Key: "artworks/sunflower-garden-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    status: "published",
    isAuctionPiece: false,
    isFeatured: true,
    description:
      "A radiant sunflower stands as a gentle sign of divine perfection, where creation is described as flawless and harmonious. Its balanced petals, ordered center, and graceful form invite the heart to look again and witness the beauty, precision, and unity woven into Allah's design.",
  },
  {
    slug: "honeycomb-flawless-design",
    title: "Flawless Design — Honeycomb",
    verseId: "al-mulk-67-3-honeycomb",
    arabic: "ٱلَّذِى خَلَقَ سَبْعَ سَمَـٰوَٰتٍ طِبَاقًا ۖ مَّا تَرَىٰ فِى خَلْقِ ٱلرَّحْمَـٰنِ مِن تَفَـٰوُتٍ ۖ فَٱرْجِعِ ٱلْبَصَرَ هَلْ تَرَىٰ مِن فُطُورٍ",
    transliteration: "Alladhī khalaqa sabʿa samāwātin ṭibāqan mā tarā fī khalqir-raḥmāni min tafāwut. Farjiʿil-baṣara hal tarā min fuṭūr",
    translation:
      "Who created the seven heavens one upon another. You will not see any inconsistency in the Merciful One's creation. Turn your vision again, can you see any flaw?",
    tafsir:
      "The honeycomb is one of nature's most perfect structures. Bees, guided by Allah's inspiration (wahy — as mentioned in Surah An-Nahl 16:68), construct hexagonal cells that use the least amount of wax to hold the most honey. Mathematicians call this the 'honeycomb conjecture' — it is the most efficient partition of a surface. Allah taught the bee this geometry. This artwork reflects on how even the smallest creatures carry the mark of Al-Khaliq, the Creator whose design knows no flaw.",
    surah: "Al-Mulk",
    surahNumber: 67,
    ayah: 3,
    theme: "Creation",
    previewImageUrl: "/artworks/honeycomb.png",
    highResS3Key: "artworks/honeycomb-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    status: "published",
    isAuctionPiece: false,
    isFeatured: false,
    description:
      "The creation of Allah is marked by balance, precision, and flawless design. The perfect geometry of the hexagonal cells invites the eye to look again and again, yet find no disorder, only beauty, wisdom, and proportion in what He has created.",
  },
  {
    slug: "mountains-raised-in-measure",
    title: "Mountains Raised in Measure",
    verseId: "al-ghashiyah-88-19",
    arabic: "وَإِلَى ٱلْجِبَالِ كَيْفَ نُصِبَتْ",
    transliteration: "Wa ilal-jibāli kayfa nuṣibat",
    translation: "And the mountains: how they were fixed?",
    tafsir:
      "This verse is part of a series of rhetorical questions in Surah Al-Ghashiyah where Allah draws attention to His signs in creation — the camel, the sky, the mountains, and the earth. Ibn Kathir explains that mountains serve as pegs (awtad) that stabilise the earth's crust, preventing it from shaking. Modern geology confirms that mountains have deep roots extending far beneath the surface. The word 'nusibat' (fixed/erected) implies deliberate placement with purpose and wisdom. Every mountain stands as a monument to divine engineering.",
    surah: "Al-Ghashiyah",
    surahNumber: 88,
    ayah: 19,
    theme: "Creation",
    previewImageUrl: "/artworks/mountains.png",
    highResS3Key: "artworks/mountains-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    status: "published",
    isAuctionPiece: false,
    isFeatured: false,
    description:
      "A majestic canyon of layered mountains rises in flowing bands of gold, rose, and amber, while still pools of turquoise water rest below. The scene feels sculpted with precision and grandeur, capturing the quiet power and beauty of mountains raised in perfect measure.",
  },
  {
    slug: "birds-in-flight-divine-mercy",
    title: "Birds in Flight",
    verseId: "al-mulk-67-19",
    arabic: "أَوَلَمْ يَرَوْا۟ إِلَى ٱلطَّيْرِ فَوْقَهُمْ صَـٰٓفَّـٰتٍ وَيَقْبِضْنَ ۚ مَا يُمْسِكُهُنَّ إِلَّا ٱلرَّحْمَـٰنُ ۚ إِنَّهُ بِكُلِّ شَىْءٍۭ بَصِيرٌ",
    transliteration: "Awalam yaraw ilat-ṭayri fawqahum ṣāffātin wa yaqbiḍn. Mā yumsikuhunna illar-raḥmān. Innahū bikulli shay'in baṣīr",
    translation:
      "Have they not seen birds above them spreading and closing their wings, with none holding them except the Merciful One? He oversees everything.",
    tafsir:
      "At-Tabari explains that this verse highlights a miracle we witness daily but rarely reflect upon: birds defy gravity. They spread their wings (saffat) and fold them (yaqbidn), yet they do not fall. The laws of aerodynamics, air pressure, and wing design all work in harmony — but who set these laws in motion? Allah answers: none holds them aloft except Ar-Rahman. The verse ends with a reminder that He is 'Baseer' — All-Seeing. The One who holds every bird in the sky also sees every detail of your life.",
    surah: "Al-Mulk",
    surahNumber: 67,
    ayah: 19,
    theme: "Mercy",
    previewImageUrl: "/artworks/birds-in-flight.png",
    highResS3Key: "artworks/birds-in-flight-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    status: "published",
    isAuctionPiece: false,
    isFeatured: false,
    description:
      "Wings open and fold in perfect rhythm, yet nothing about their flight feels self-sustained. Beauty, motion, and mercy meet in a single breath of air.",
  },
  // ─── NEW 8 ARTWORKS ───
  {
    slug: "water-droplet-divine-precision",
    title: "Water Droplet — Divine Precision",
    verseId: "al-mulk-67-3-water-droplet",
    arabic: "ٱلَّذِى خَلَقَ سَبْعَ سَمَـٰوَٰتٍ طِبَاقًا ۖ مَّا تَرَىٰ فِى خَلْقِ ٱلرَّحْمَـٰنِ مِن تَفَـٰوُتٍ ۖ فَٱرْجِعِ ٱلْبَصَرَ هَلْ تَرَىٰ مِن فُطُورٍ",
    transliteration: "Alladhī khalaqa sabʿa samāwātin ṭibāqan mā tarā fī khalqir-raḥmāni min tafāwut. Farjiʿil-baṣara hal tarā min fuṭūr",
    translation: "Who created the seven heavens one upon another. You will not see any inconsistency in the Merciful One's creation. Turn your vision again, can you see any flaw?",
    tafsir: "A single water droplet resting on a leaf holds within it the reflection of an entire world. Surface tension, light refraction, the curvature of the meniscus — all governed by precise physical laws that Allah set in motion. This verse challenges us to find a single flaw in the Merciful One's creation. The droplet is a microcosm of that challenge: perfect in form, balanced by forces invisible to the eye, and beautiful beyond what chance could produce.",
    surah: "Al-Mulk",
    surahNumber: 67,
    ayah: 3,
    theme: "Creation",
    previewImageUrl: "/artworks/water-droplet-divine-precision.png",
    highResS3Key: "artworks/water-droplet-divine-precision-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    status: "published",
    isAuctionPiece: false,
    isFeatured: true,
    description: "A crystal-clear water droplet balances on a leaf, reflecting the world within. A meditation on the flawless precision woven into the smallest details of Allah's creation.",
  },
  {
    slug: "tree-rings-divine-precision",
    title: "Tree Rings — Divine Precision",
    verseId: "al-mulk-67-3-tree-rings",
    arabic: "ٱلَّذِى خَلَقَ سَبْعَ سَمَـٰوَٰتٍ طِبَاقًا ۖ مَّا تَرَىٰ فِى خَلْقِ ٱلرَّحْمَـٰنِ مِن تَفَـٰوُتٍ ۖ فَٱرْجِعِ ٱلْبَصَرَ هَلْ تَرَىٰ مِن فُطُورٍ",
    transliteration: "Alladhī khalaqa sabʿa samāwātin ṭibāqan mā tarā fī khalqir-raḥmāni min tafāwut. Farjiʿil-baṣara hal tarā min fuṭūr",
    translation: "Who created the seven heavens one upon another. You will not see any inconsistency in the Merciful One's creation. Turn your vision again, can you see any flaw?",
    tafsir: "Each ring of a tree records a year of growth — seasons of rain and drought, warmth and cold, all inscribed in concentric circles of perfect proportion. The cross-section of a tree trunk reveals layers upon layers (tibaqan), echoing the very word Allah uses to describe the seven heavens. No two rings are identical, yet the whole is harmonious. The tree grows outward from its centre with mathematical regularity, a living record of time shaped by the hand of Al-Khaliq.",
    surah: "Al-Mulk",
    surahNumber: 67,
    ayah: 3,
    theme: "Creation",
    previewImageUrl: "/artworks/tree-rings-divine-precision.png",
    highResS3Key: "artworks/tree-rings-divine-precision-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    status: "published",
    isAuctionPiece: false,
    isFeatured: false,
    description: "Concentric rings of a tree trunk reveal years of growth in perfect proportion — layers upon layers, echoing the heavens created one upon another.",
  },
  {
    slug: "luminous-niche-light-verse",
    title: "The Luminous Niche — Light Verse",
    verseId: "an-nur-24-35",
    arabic: "ٱللَّهُ نُورُ ٱلسَّمَـٰوَٰتِ وَٱلْأَرْضِ ۚ مَثَلُ نُورِهِۦ كَمِشْكَوٰةٍ فِيهَا مِصْبَاحٌ ۖ ٱلْمِصْبَاحُ فِى زُجَاجَةٍ ۖ ٱلزُّجَاجَةُ كَأَنَّهَا كَوْكَبٌ دُرِّىٌّ",
    transliteration: "Allāhu nūrus-samāwāti wal-arḍ. Mathalu nūrihī kamishkātin fīhā miṣbāḥ. Al-miṣbāḥu fī zujājah. Az-zujājatu ka'annahā kawkabun durriyy",
    translation: "Allah is the Light of the heavens and the earth. His light is like a niche in which there is a lamp. The lamp is in a glass. The glass is like a radiant star.",
    tafsir: "This is Ayat an-Nur — the Verse of Light — one of the most profound and mystical verses in the Quran. Allah describes His light through a layered metaphor: a niche (mishkat) containing a lamp, the lamp enclosed in glass brilliant as a star, fuelled by blessed olive oil that almost glows on its own. Each layer — niche, lamp, glass, oil — represents degrees of divine guidance. The scholars say the niche is the believer's chest, the lamp is faith, the glass is the heart purified by iman, and the oil is the fitrah that inclines toward truth even before revelation touches it. Light upon light — nur ala nur.",
    surah: "An-Nur",
    surahNumber: 24,
    ayah: 35,
    theme: "Light",
    previewImageUrl: "/artworks/luminous-niche-light-verse.png",
    highResS3Key: "artworks/luminous-niche-light-verse-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    status: "published",
    isAuctionPiece: false,
    isFeatured: true,
    description: "A luminous niche glows with sacred light — the lamp within the glass, the glass like a brilliant star. A visual meditation on Ayat an-Nur, the Verse of Light.",
  },
  {
    slug: "seashell-determined-measure",
    title: "Seashell — Determined Measure",
    verseId: "al-qamar-54-49-seashell",
    arabic: "إِنَّا كُلَّ شَىْءٍ خَلَقْنَـٰهُ بِقَدَرٍ",
    transliteration: "Innā kulla shay'in khalaqnāhu biqadar",
    translation: "Indeed, We have created everything in a determined measure.",
    tafsir: "This verse affirms that nothing in creation is accidental. The word 'qadar' means precise measure, proportion, and predestination. A seashell grows according to a logarithmic spiral — a mathematical curve that maintains its shape at every scale. The ridges, the symmetry, the proportions — all follow rules encoded by Allah before the shell ever formed. The scholars explain that 'qadar' encompasses both the divine decree (what will happen) and the divine design (how things are made). Every atom, every cell, every shell ridge exists by appointment.",
    surah: "Al-Qamar",
    surahNumber: 54,
    ayah: 49,
    theme: "Creation",
    previewImageUrl: "/artworks/seashell-determined-measure.png",
    highResS3Key: "artworks/seashell-determined-measure-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    status: "published",
    isAuctionPiece: false,
    isFeatured: false,
    description: "A seashell's perfect ridges and curves — grown not by chance but by divine measure. Every line, every proportion, appointed by the Creator.",
  },
  {
    slug: "feather-determined-measure",
    title: "Feather — Determined Measure",
    verseId: "al-qamar-54-49-feather",
    arabic: "إِنَّا كُلَّ شَىْءٍ خَلَقْنَـٰهُ بِقَدَرٍ",
    transliteration: "Innā kulla shay'in khalaqnāhu biqadar",
    translation: "Indeed, We have created everything in a determined measure.",
    tafsir: "A single feather is an engineering marvel: the central shaft (rachis) branches into barbs, which branch into barbules, which interlock with tiny hooks (hamuli) to form an airtight surface. This fractal branching pattern, repeated at multiple scales, enables flight, insulation, and waterproofing — all from keratin, the same protein in human fingernails. The feather did not design itself. It was created biqadar — with a determined measure that science continues to study but cannot replicate.",
    surah: "Al-Qamar",
    surahNumber: 54,
    ayah: 49,
    theme: "Creation",
    previewImageUrl: "/artworks/feather-determined-measure.png",
    highResS3Key: "artworks/feather-determined-measure-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    status: "published",
    isAuctionPiece: false,
    isFeatured: false,
    description: "A solitary feather rests in quiet beauty — its barbs, barbules, and hooks all engineered with precision. Created in a determined measure.",
  },
  {
    slug: "nautilus-determined-measure",
    title: "Nautilus — Determined Measure",
    verseId: "al-qamar-54-49-nautilus",
    arabic: "إِنَّا كُلَّ شَىْءٍ خَلَقْنَـٰهُ بِقَدَرٍ",
    transliteration: "Innā kulla shay'in khalaqnāhu biqadar",
    translation: "Indeed, We have created everything in a determined measure.",
    tafsir: "The nautilus shell is one of nature's most celebrated examples of mathematical beauty. Its cross-section reveals chambers arranged in a logarithmic spiral that approximates the golden ratio. As the creature grows, each new chamber is larger than the last by a fixed proportion — the same proportion found in galaxies, hurricanes, and the arrangement of seeds in a sunflower. This is qadar made visible: a living creature building its home according to a mathematical law it does not know, following a design written by the One who created everything in determined measure.",
    surah: "Al-Qamar",
    surahNumber: 54,
    ayah: 49,
    theme: "Creation",
    previewImageUrl: "/artworks/nautilus-determined-measure.png",
    highResS3Key: "artworks/nautilus-determined-measure-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    status: "published",
    isAuctionPiece: false,
    isFeatured: false,
    description: "The nautilus spiral — chambers growing in golden proportion, a living testament to the determined measure woven into every created thing.",
  },
  {
    slug: "pinecone-determined-measure",
    title: "Pine Cone — Determined Measure",
    verseId: "al-qamar-54-49-pinecone",
    arabic: "إِنَّا كُلَّ شَىْءٍ خَلَقْنَـٰهُ بِقَدَرٍ",
    transliteration: "Innā kulla shay'in khalaqnāhu biqadar",
    translation: "Indeed, We have created everything in a determined measure.",
    tafsir: "A pine cone's scales spiral in two directions — typically 8 spirals one way and 13 the other, both consecutive Fibonacci numbers. This pattern maximises the packing efficiency of seeds, ensuring each one receives equal light and space. The pine cone does not count; it does not calculate. It simply grows according to the measure Allah placed within its genetic code. Ibn al-Qayyim wrote that every created thing is a sign (ayah) for those who reflect. The pine cone is one such sign — small, humble, yet carrying the fingerprint of infinite wisdom.",
    surah: "Al-Qamar",
    surahNumber: 54,
    ayah: 49,
    theme: "Creation",
    previewImageUrl: "/artworks/pinecone-determined-measure.png",
    highResS3Key: "artworks/pinecone-determined-measure-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    status: "published",
    isAuctionPiece: false,
    isFeatured: false,
    description: "Fibonacci spirals in a pine cone — 8 one way, 13 the other — a humble sign of the determined measure placed in every created thing.",
  },
  {
    slug: "flower-bud-determined-measure",
    title: "Flower Bud — Determined Measure",
    verseId: "al-qamar-54-49-flower-bud",
    arabic: "إِنَّا كُلَّ شَىْءٍ خَلَقْنَـٰهُ بِقَدَرٍ",
    transliteration: "Innā kulla shay'in khalaqnāhu biqadar",
    translation: "Indeed, We have created everything in a determined measure.",
    tafsir: "A flower bud holds within it the promise of bloom — petals folded in precise overlapping layers, pigments already mixed, fragrance already composed, all waiting for the appointed moment to unfold. The bud does not rush; it opens when Allah's measure dictates. Imam al-Ghazali saw in flowers a parable of divine artistry: the colours are painted without a brush, the symmetry is drawn without a compass, and the fragrance is composed without a perfumer. Everything — from the curve of each petal to the moment of its opening — is created biqadar.",
    surah: "Al-Qamar",
    surahNumber: 54,
    ayah: 49,
    theme: "Creation",
    previewImageUrl: "/artworks/flower-bud-determined-measure.png",
    highResS3Key: "artworks/flower-bud-determined-measure-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    status: "published",
    isAuctionPiece: false,
    isFeatured: true,
    description: "A rose bud on the verge of bloom — petals folded in precise layers, waiting for the appointed moment. Everything created in determined measure.",
  },
  // ─── HORIZONTAL ARTWORKS ───
  {
    slug: "ocean-reflection-words-of-allah",
    title: "Words of Allah — Ocean Reflection",
    verseId: "luqman-31-27",
    arabic: "وَلَوْ أَنَّمَا فِى ٱلْأَرْضِ مِن شَجَرَةٍ أَقْلَـٰمٌ وَٱلْبَحْرُ يَمُدُّهُۥ مِنۢ بَعْدِهِۦ سَبْعَةُ أَبْحُرٍ مَّا نَفِدَتْ كَلِمَـٰتُ ٱللَّهِ ۗ إِنَّ ٱللَّهَ عَزِيزٌ حَكِيمٌ",
    transliteration: "Wa law annamā fil-arḍi min shajaratin aqlāmun wal-baḥru yamudduhu min baʿdihi sabʿatu abḥurin mā nafidat kalimātullāh. Innallāha ʿazīzun ḥakīm",
    translation: "If all the trees on earth were pens and the ocean were ink, refilled by seven other oceans, the Words of Allah would not be exhausted. Surely Allah is Almighty, All-Wise.",
    tafsir: "This verse illustrates the infinite nature of Allah's knowledge and speech. If every tree on earth were turned into a pen and the oceans multiplied seven times over as ink, they would still run dry before Allah's words could be fully written. The scholars explain that the 'Words of Allah' (kalimatullah) encompass His knowledge, His wisdom, His decrees, and the signs of His creation. This is not hyperbole — it is a statement of literal truth about the infinite scope of divine knowledge compared to the finite capacity of all creation combined.",
    surah: "Luqman",
    surahNumber: 31,
    ayah: 27,
    theme: "Knowledge",
    previewImageUrl: "/artworks/ocean-reflection-words-of-allah.png",
    highResS3Key: "artworks/ocean-reflection-words-of-allah-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    orientation: "horizontal",
    status: "published",
    isAuctionPiece: false,
    isFeatured: true,
    description: "A vast ocean reflects the sky in perfect stillness — a visual meditation on the limitless Words of Allah that no ocean of ink could ever exhaust.",
  },
  {
    slug: "piercing-star-night-sky",
    title: "The Piercing Star",
    verseId: "at-tariq-86-1",
    arabic: "وَٱلسَّمَآءِ وَٱلطَّارِقِ ۞ وَمَآ أَدْرَىٰكَ مَا ٱلطَّارِقُ ۞ ٱلنَّجْمُ ٱلثَّاقِبُ",
    transliteration: "Was-samā'i waṭ-ṭāriq. Wa mā adrāka maṭ-ṭāriq. An-najmuth-thāqib",
    translation: "And what will make you realize what the nightly star is? It is the star of piercing brightness.",
    tafsir: "Allah swears by the sky and the 'tariq' — the night visitor, the piercing star. The word 'thaqib' means something that penetrates, that pierces through. The scholars identify this as a reference to stars of exceptional brightness that appear to bore through the darkness of the night sky. Some modern commentators connect this to pulsars — rapidly rotating neutron stars that emit beams of electromagnetic radiation, literally piercing through space. Whether a brilliant planet, a shooting star, or a pulsar, the oath draws attention to the power of the One who placed it there.",
    surah: "At-Tariq",
    surahNumber: 86,
    ayah: 1,
    theme: "Creation",
    previewImageUrl: "/artworks/piercing-star-night-sky.png",
    highResS3Key: "artworks/piercing-star-night-sky-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    orientation: "horizontal",
    status: "published",
    isAuctionPiece: false,
    isFeatured: false,
    description: "A brilliant star pierces the desert night — radiating light that cuts through the darkness, a sign of the One who set it ablaze.",
  },
  {
    slug: "expanding-universe",
    title: "The Expanding Universe",
    verseId: "adh-dhariyat-51-47",
    arabic: "وَٱلسَّمَآءَ بَنَيْنَـٰهَا بِأَيْىدٍ وَإِنَّا لَمُوسِعُونَ",
    transliteration: "Was-samā'a banaynāhā bi'aydin wa innā lamūsiʿūn",
    translation: "We built the universe with great might, and We are certainly expanding it.",
    tafsir: "This verse, revealed in the 7th century, describes the expansion of the universe — a fact that science only confirmed in 1929 when Edwin Hubble observed that galaxies are moving away from each other. The word 'musi'un' comes from 'wasi'a' meaning to expand, widen, or make vast. Allah states this as an ongoing action: 'We are certainly expanding it.' The cosmic microwave background radiation, the redshift of distant galaxies, and the accelerating expansion of space all testify to what this verse declared over 1,400 years ago.",
    surah: "Adh-Dhariyat",
    surahNumber: 51,
    ayah: 47,
    theme: "Creation",
    previewImageUrl: "/artworks/expanding-universe.png",
    highResS3Key: "artworks/expanding-universe-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    orientation: "horizontal",
    status: "published",
    isAuctionPiece: false,
    isFeatured: true,
    description: "A cosmic expanse of stars, nebulae, and light — the universe stretching outward in every direction, built with great might and ever-expanding.",
  },
  {
    slug: "rocky-coastline-vision",
    title: "Rocky Coastline — Turn Your Vision",
    verseId: "al-mulk-67-4",
    arabic: "ثُمَّ ٱرْجِعِ ٱلْبَصَرَ كَرَّتَيْنِ يَنقَلِبْ إِلَيْكَ ٱلْبَصَرُ خَاسِئًا وَهُوَ حَسِيرٌ",
    transliteration: "Thummar-jiʿil-baṣara karratayni yanqalib ilaykal-baṣaru khāsi'an wa huwa ḥasīr",
    translation: "Then turn your vision again, and then again; in the end your vision will come back to you, worn out and frustrated.",
    tafsir: "This verse continues the challenge from 67:3. After looking once for a flaw in creation and finding none, Allah says: look again — and again. The word 'karratain' literally means 'twice,' but scholars say it implies repeated, persistent looking. And the result? Your vision returns 'khasi'an' (humbled, defeated) and 'hasir' (exhausted, frustrated). The more deeply you examine creation — from the geological forces that carved coastlines to the physics of crashing waves — the more perfection you find. Human vision tires before divine design reveals a single fault.",
    surah: "Al-Mulk",
    surahNumber: 67,
    ayah: 4,
    theme: "Creation",
    previewImageUrl: "/artworks/rocky-coastline-vision.png",
    highResS3Key: "artworks/rocky-coastline-vision-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    orientation: "horizontal",
    status: "published",
    isAuctionPiece: false,
    isFeatured: false,
    description: "Golden cliffs meet the sea in dramatic grandeur — turn your vision again and again, yet find no flaw in the Creator's design.",
  },
  {
    slug: "clouds-lightning-divine",
    title: "Clouds & Lightning — Divine Majesty",
    verseId: "an-nur-24-43",
    arabic: "أَلَمْ تَرَ أَنَّ ٱللَّهَ يُزْجِى سَحَابًا ثُمَّ يُؤَلِّفُ بَيْنَهُۥ ثُمَّ يَجْعَلُهُۥ رُكَامًا فَتَرَى ٱلْوَدْقَ يَخْرُجُ مِنْ خِلَـٰلِهِۦ",
    transliteration: "Alam tara annallāha yuzjī saḥāban thumma yu'allifu baynahū thumma yajʿaluhu rukāman fatara l-wadqa yakhruju min khilālih",
    translation: "Do you not see that Allah gently drives the clouds, then joins them together, piling them up into masses, from which you see raindrops come forth?",
    tafsir: "This verse describes the water cycle and cloud formation with remarkable precision. Allah 'yuzji' (gently drives) clouds — referring to wind moving water vapour. Then He 'yu'allifu baynahū' (joins them together) — small clouds merging. Then 'yaj'aluhu rukaman' (makes them into piles/masses) — cumulonimbus tower formation. Then rain emerges 'min khilalihi' (from within it). And later in the verse, hail and lightning are mentioned. This sequence — evaporation, condensation, cloud merging, towering formation, precipitation — matches exactly what meteorology describes. The verse also mentions that lightning nearly blinds the sight, and that Allah alternates night and day — connecting weather, light, and divine power.",
    surah: "An-Nur",
    surahNumber: 24,
    ayah: 43,
    theme: "Creation",
    previewImageUrl: "/artworks/clouds-lightning-divine.png",
    highResS3Key: "artworks/clouds-lightning-divine-highres.png",
    digitalPrice: 99900,
    printPriceBase: 499900,
    printSizes: defaultPrintSizes,
    frameOptions: defaultFrameOptions,
    orientation: "horizontal",
    status: "published",
    isAuctionPiece: false,
    isFeatured: false,
    description: "Towering clouds gather and pile into masses as light breaks through — a scene of divine majesty where rain, hail, and lightning reveal Allah's power over the skies.",
  },
];

async function seed() {
  console.log("Connecting to MongoDB...");
  await mongoose.connect(MONGODB_URI);
  console.log("Connected!");

  // Clear existing artworks
  await Artwork.deleteMany({});
  console.log("Cleared existing artworks.");

  // Insert new artworks
  for (const art of artworks) {
    await Artwork.create(art);
    console.log(`✓ Added: ${art.slug}`);
  }

  console.log(`\nDone! ${artworks.length} artworks seeded.`);
  console.log("Featured: 3 (Sibghatallah, Lote Trees, Sunflower Garden)");
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("Seed error:", err);
  process.exit(1);
});
